services:
    web:
        build: .
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - LOG_CHANNEL=${LOG_CHANNEL}
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy # Disable this if you are using an external Postgres database
    db:
        image: postgres:16-alpine
        healthcheck:
            test: pg_isready -U postgres -h localhost
            interval: 5s
            timeout: 5s
            retries: 10
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5433:5432"
