services:
    web:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - VIRTUAL_HOST=localhost
        depends_on:
            - db

    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laravelpassword
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
