services:
    web:
        build: .
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - LOG_CHANNEL=${LOG_CHANNEL}
        depends_on:
            - db
    db:
        image: mysql:8
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: laravelpassword
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
